#!/usr/bin/env bash
# bootstrap <cucoo-dir>

set -e          # fail fast
set -o pipefail # fail through pipe
# set -x

config_dir=$(cd $(dirname $0); cd ..; pwd)
source $config_dir/script/common.sh

cuckoo_dir=${1:-$DEFAULT_CUCKOO_DIR}
python2=`which python2.7`

mkdir -p $cuckoo_dir
cd $cuckoo_dir

say "installing dependencies"
sudo pacman --needed --noconfirm -S python-virtualenv python2-yara python-yara \
                                    yara tcpdump tesseract tesseract-data-por \
                                    tesseract-data-eng mongodb | indent

if ! (test -f $cuckoo_dir/cuckoo.py); then
  say "installing cuckoo"
  mkdir -p $cuckoo_dir/tmp
  cd $cuckoo_dir/tmp
  curl -L -O https://downloads.cuckoosandbox.org/cuckoo-current.tar.gz
  tar xf cuckoo-current.tar.gz | indent
  cp -R ./cuckoo/* $cuckoo_dir
  cd $cuckoo_dir
  rm -rf $cuckoo_dir/tmp
fi

if ! (test -d $cuckoo_dir/venv); then
  say "creating virtualenv on $cuckoo_dir/venv"
  virtualenv --system-site-packages -p $python2 venv | indent
fi

# enter virtualenv
source venv/bin/activate

say "overriding requirements.txt"
cp $config_dir/requirements.txt $cuckoo_dir/requirements.txt

say "installing dependencies"
pip install -q -r requirements.txt | indent

say "copying config files to $cuckoo_dir/conf"
cp $config_dir/conf/*.conf "$cuckoo_dir/conf/"

# exit virtualenv
deactivate
