#!/usr/bin/env bash
# server <cucoo-dir>

set -e          # fail fast
set -o pipefail # fail through pipe
# set -x

config_dir=$(cd $(dirname $0); cd ..; pwd)
source $config_dir/script/common.sh

cuckoo_dir=${1:-$DEFAULT_CUCKOO_DIR}

say "updating"
$config_dir/script/update

cd $cuckoo_dir

# enter virtualenv
source venv/bin/activate

say "running services"
for service in mongodb.service; do
  if ! systemctl status $service > /dev/null; then
    systemctl restart $service
  fi
done

say "running cuckoo"
python cuckoo.py

# exit virtualenv
deactivate
