#!/usr/bin/env bash
# setup <cucoo-dir>

set -e          # fail fast
set -o pipefail # fail through pipe
# set -x

config_dir=$(cd $(dirname $0); cd ..; pwd)
source $config_dir/script/common.sh

cuckoo_dir=${1:-$DEFAULT_CUCKOO_DIR}

say "bootstraping"
$config_dir/script/bootstrap

if ! groups $USER | \grep "pcap" > /dev/null; then
  say "add tcpdump permissions for current user"
  sudo groupadd pcap
  sudo usermod -aG pcap $USER
  sudo chgrp pcap /etc/sbin/tcpdump
  chmod 750 /etc/sbin/tcpdump
  setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
fi

cd $cuckoo_dir

# enter virtualenv
source venv/bin/activate

echo
say "TODO: create a VM automagically"
echo

# exit virtualenv
deactivate
