#!/usr/bin/env bash
# setup <cucoo-dir>

set -e          # fail fast
set -o pipefail # fail through pipe
# set -x

config_dir=$(cd $(dirname $0); cd ..; pwd)
source $config_dir/script/common.sh

cuckoo_dir=${1:-$DEFAULT_CUCKOO_DIR}

say "bootstraping"
$config_dir/script/bootstrap

say "installing dependencies"
sudo pacman -S tcpdump tesseract tesseract-data-por tesseract-data-end mongodb

cd $cuckoo_dir

# enter virtualenv
source venv/bin/activate

echo
say "TODO: create a VM automagically"
echo

# exit virtualenv
deactivate
