#!/usr/bin/env bash
# bootstrap <cucoo-dir>

set -e          # fail fast
set -o pipefail # fail through pipe
# set -x

config_dir=$(cd $(dirname $0); cd ..; pwd)
source $config_dir/script/common.sh

cuckoo_dir=${1:-$DEFAULT_CUCKOO_DIR}

cd $cuckoo_dir

$config_dir/script/bootstrap
